### ISSUE TITLE
send message in batch mode do not work

### ISSUE THREAD

**Issue by xiuliren** [samoconnor/AWSSQS.jl#4]
sending single message works, but not in batch mode.

```julia
msgs = repeat(["test message"], outer = 10)
sqs_send_message_batch(q, msgs) # this do not work   
sqs_send_message(q, msgs[1]) # this works
```

error
```
ERROR: AWS.SimpleQueueService.EmptyBatchRequest -- There should be at least one SendMessageBatchRequestEntry in the request.
HTTP.StatusError: received a '400 - Bad Request' status in response

Stacktrace:
 [1] macro expansion at /Users/jpwu/.julia/v0.6/Retry/src/repeat_try.jl:162 [inlined]
 [2] do_request(::Dict{Symbol,Any}) at /Users/jpwu/.julia/v0.6/AWSCore/src/AWSCore.jl:394
 [3] #service_query#9(::Array{Any,1}, ::Function, ::Dict{Symbol,Any}) at /Users/jpwu/.julia/v0.6/AWSCore/src/AWSCore.jl:240
 [4] (::AWSCore.#kw##service_query)(::Array{Any,1}, ::AWSCore.#service_query, ::Dict{Symbol,Any}) at ./<missing>:0
 [5] (::AWSSQS.#kw##sqs)(::Array{Any,1}, ::AWSSQS.#sqs, ::Dict{Symbol,Any}, ::String) at ./<missing>:0
 [6] sqs_send_message_batch(::Dict{Symbol,Any}, ::String) at /Users/jpwu/.julia/v0.6/AWSSQS/src/AWSSQS.jl:220
```

I am testing in Julia 0.6. BTW, there is no test for batch mode in runtests.jl

also, batch mode only works with a maximum number of 10 messages! This was not included in the code.

**Comment by samoconnor** [comment]
Hi @jingpengw, please try the commits to AWSQS.jl and AWSCore.jl referenced above.

If you'd like to submit a PR for a batch mode test, that'd be great! ;)

Regarding the 10-message limit, It looks like the error message returned is fairly clear:
```julia
ERROR: AWS.SimpleQueueService.TooManyEntriesInBatchRequest
 -- Maximum number of entries per request are 10. You have sent 11.
```

It is not my intention to implement input validation for all of the messages sent to AWS. Particularly if the error message is easy to understand, I'd rather leave that to the server side. Perhaps AWS will increase the limit from 10 to 100 at some point? Perhaps it is already possible to have the limit increased on a per-account basis through an AWS support contract? Best not to lock this stuff in on the client side IMHO.

**Comment by xiuliren** [comment]
Thanks for the fix! Just created a PR to add test for batch mode.
Ignoring the maximum number of entries per request sounds reasonable to me.

**Comment by samoconnor** [comment]
Note also the new simple interface for SQS that is build into AWSCore:  https://juliacloud.github.io/AWSCore.jl/build/AWSSDK.SQS.html#AWSSDK.SQS.send_message_batch

e.g.
```julia
using AWSCore.Services.sqs
sqs("SendMessageBatch",
 QueueUrl=url,
 SendMessageBatchRequestEntry=[
    ["Id" => 1, "MessageBody" => "foo"],
    ["Id" => 2, "MessageBody" => "bar"]
])
```
